RENAME_MAPPINGS = [
    ("Anonymous Chunk.Willow_V1.1", "Anonymous Chunk.Alyson Hannigan.1"),
    ("Anonymous Chunk.Miss_Diaz_V1.1", "Anonymous Chunk.Cameron Diaz.1"),
    ("Anonymous Chunk.Cam_Mendes_V1.1", "Anonymous Chunk.Camila Mendes.1"),
    ("Anonymous Chunk.Christina_R_V1.1", "Anonymous Chunk.Christina Ricci.1"),
    ("Anonymous Chunk.The_Molsens.1", "Anonymous Chunk.Elizabeth Olsen_sisters.1"),
    ("Anonymous Chunk.Wanda_V2.1", "Anonymous Chunk.Elizabeth Olsen.1"),
    ("Anonymous Chunk.Gemma_M_V1.1", "Anonymous Chunk.Gemma Merna.1"),
    ("Anonymous Chunk.Emily_In_Paris.1", "Anonymous Chunk.Lily Collins.1"),
    ("Anonymous Chunk.Megan_Rain_V1.1", "Anonymous Chunk.Megan Rain.1"),
    ("Anonymous Chunk.LeeLoo_Dallas_V2_1.1", "Anonymous Chunk.Milla Jovich.1"),
    ("Anonymous Chunk.Nadine_Bret_V1.1", "Anonymous Chunk.Nadine Breaty.1"),
    ("Anonymous Chunk.Rachel_B_V1.1", "Anonymous Chunk.Rachel Bilson.1"),
    ("Anonymous Chunk.Ygritte_V1.2", "Anonymous Chunk.Rose Leslie.2"),
    ("Anonymous Chunk.Finnish_PM_V1.1", "Anonymous Chunk.Sanna Marin Finnish Pm.1"),
    ("Azur.Ginny_V3.1", "Azur.Bonnie Wright.1"),
    ("Azur.EmmaWotsan_V3.1", "Azur.Emma Watson.1"),
    ("Azur.Luna_V3.1", "Azur.Evanna Lynch.1"),
    ("Azur.GrethDoomberg_V3.1", "Azur.Greta Thunberg.1"),
    ("Bamair1984.Alexander_Torresi.1", "Bamair1984.Alexandra Siegel.1"),
    ("Bamair1984.Laliza_HD.1", "Bamair1984.Alizee.1"),
    ("Bamair1984.Alyson_HaneyV3.3", "Bamair1984.Alyson Hannigan.3"),
    ("Bamair1984.No_Time_To_SEX.1", "Bamair1984.Ana De Armas.1"),
    ("Bamair1984.ArianaJan_HD.1", "Bamair1984.Ariana Grande.1"),
    ("Bamair1984.BeyonHD2.1", "Bamair1984.Beyonce.1"),
    ("Bamair1984.Britney_PearsonV3.1", "Bamair1984.Britney Spears.1"),
    ("Bamair1984.Z_JonesV3.3", "Bamair1984.Catherine Zeta Jones.3"),
    ("Bamair1984.NA-EUM.1", "Bamair1984.Cheong Eum.1"),
    ("Bamair1984.ChristinaR_V3.1", "Bamair1984.Christina Ricci.1"),
    ("Bamair1984.Dilraba_HD_V12.2", "Bamair1984.Dilraba Dilmurat.2"),
    ("Bamair1984.Elise_Turley_HD.1", "Bamair1984.Elizabeth Hurley.1"),
    ("Bamair1984.Elizabeth_Orson_HD.1", "Bamair1984.Elizabeth Olsen.1"),
    ("Bamair1984.Emilia_Cora.1", "Bamair1984.Emilia Clarke.1"),
    ("Bamair1984.Emma_Robinson_V22.1", "Bamair1984.Emma Roberts_v2.1"),
    ("Bamair1984.Madison_Montgomery_HD.1", "Bamair1984.Emma Roberts.1"),
    ("Bamair1984.Emma_MaxV3.1", "Bamair1984.Emma Stone.1"),
    ("Bamair1984.Emma_Smith_HD.2", "Bamair1984.Emma Stone.2"),
    ("Bamair1984.Emma_Wilson_V25.1", "Bamair1984.Emma Watson_v2.1"),
    ("Bamair1984.EnnA_HD.1", "Bamair1984.Emma Watson.1"),
    ("Bamair1984.Princess_Ann.1", "Bamair1984.Erin Doherty.1"),
    ("Bamair1984.GraceKate_HD.1", "Bamair1984.Grace Van Dien.1"),
    ("Bamair1984.Halle_B.1", "Bamair1984.Halle Berry.1"),
    ("Bamair1984.HeatherGra_HD.2", "Bamair1984.Heather Graham.2"),
    ("Bamair1984.NayonHD1_2.1", "Bamair1984.Im Na-Yeon.1"),
    ("Bamair1984.Denny_Fischer.1", "Bamair1984.Jenna Fischer_young.1"),
    ("Bamair1984.Jenna_Faith.1", "Bamair1984.Jenna Fischer.1"),
    ("Bamair1984.RhonaMira.1", "Bamair1984.Jennifer Aniston.1"),
    ("Bamair1984.Miss_Jennifer.1", "Bamair1984.Jennifer Lawrence.1"),
    ("Bamair1984.Jennifer_Young.2", "Bamair1984.Jennifer Love Hewitt.2"),
    ("Bamair1984.Emma_V31.1", "Bamair1984.Jenny Ortega_emma.1"),
    ("Bamair1984.Jenna_V33.1", "Bamair1984.Jenny Ortega.1"),
    ("Bamair1984.Wednesday_Collection.1", "Bamair1984.Jenny Ortega_wednesday.1"),
    ("Bamair1984.Jessie_RoseV3.1", "Bamair1984.Jessica Roth.1"),
    ("Bamair1984.Kelly_Coco_HD.1", "Bamair1984.Kaley Cuoco.1"),
    ("Bamair1984.Karen_GlennV3.2", "Bamair1984.Karen Gillan.2"),
    ("Bamair1984.KateBecki&Selena_Update.1", "Bamair1984.Kate Beckinsale.1"),
    ("Bamair1984.KateUptonyHD.1", "Bamair1984.Kate Upton.1"),
    ("Bamair1984.Katie_ParrellV3.1", "Bamair1984.Katy Perry.1"),
    ("Bamair1984.Ladyfafa.1", "Bamair1984.Lady Gaga.1"),
    ("Bamair1984.Laura_PouletV32.1", "Bamair1984.Laura Prepon.1"),
    ("Bamair1984.Amy_Aiken_HD.1", "Bamair1984.Lucy Aiken.1"),
    ("Bamair1984.BarbieV3_1.1", "Bamair1984.Margot Robbie_barbie.1"),
    ("Bamair1984.Margo_Robin_V30.1", "Bamair1984.Margot Robbie.1"),
    ("Bamair1984.Harley_V3.1", "Bamair1984.Margot Robbie_harley.1"),
    ("Bamair1984.Leah_Sharipova_HD.1", "Bamair1984.Maria Sharapova.1"),
    ("Bamair1984.Melissa_HD.1", "Bamair1984.Melissa Joan Hart.1"),
    ("Bamair1984.Merry_Joan.3", "Bamair1984.Melissa Joan Hart.3"),
    ("Bamair1984.MichelleCool_HD.1", "Bamair1984.Michelle Mccool.1"),
    ("Bamair1984.Michelle_HeratbergV3.1", "Bamair1984.Michelle Trachtenberg.1"),
    ("Bamair1984.Natalie_Pott_V3.1", "Bamair1984.Natalie Portman.1"),
    ("Bamair1984.Rachel_adams_young_HD.1", "Bamair1984.Rachel Mcadams.1"),
    ("Bamair1984.RemyCroix_HD.1", "Bamair1984.Remy Lacroix.1"),
    ("Bamair1984.SarahSilman.2", "Bamair1984.Sarah Silverman.2"),
    ("Bamair1984.Scarlett_JoeV3.1", "Bamair1984.Scarlett Johansson.1"),
    ("Bamair1984.Serena_Gomes_V16.2", "Bamair1984.Selena Gomez.2"),
    ("Bamair1984.Taylor_West.1", "Bamair1984.Taylor Swift.1"),
    ("Bamair1984.Torrie_HD.2", "Bamair1984.Torrie Wilson.2"),
    ("Bamair1984.Trisy1.1", "Bamair1984.Trish Stratus.1"),
    ("BooGoo.alex_v2_3.1", "BooGoo.Alexandra Daddario.1"),
    ("BooGoo.beth_harmon_v1.1", "BooGoo.Anna Taylor Joy.1"),
    ("BooGoo.bella_v3.1", "BooGoo.Bella Poarch.1"),
    ("BooGoo.belle_v2.1", "BooGoo.Belle Delphine.1"),
    ("BooGoo.Mera_Ajui.1", "BooGoo.Blake Lively.1"),
    ("BooGoo.Blaney.1", "BooGoo.Britney Spears.1"),
    ("BooGoo.dasha_taran.1", "BooGoo.Dasha Taran.1"),
    ("BooGoo.dove_cameron.1", "BooGoo.Dove Cameron.1"),
    ("BooGoo.jennifer_v1.1", "BooGoo.Jennifer Lawrence.1"),
    ("BooGoo.jordyn_j.1", "BooGoo.Jordyn Jones.1"),
    ("BooGoo.J_Blue_girl.1", "BooGoo.Katy Perry.1"),
    ("BooGoo.kendall_v2_2.1", "BooGoo.Kendall Jenner.1"),
    ("BooGoo.kylie_v2.1", "BooGoo.Kylie Jenner.1"),
    ("BooGoo.Laorun_Meboer.1", "BooGoo.Lauren Kettering.1"),
    ("BooGoo.lauren_v1.1", "BooGoo.Lauren.1"),
    ("BooGoo.Marilyn_v2.1", "BooGoo.Marilyn Monroe.1"),
    ("BooGoo.Spider-Gwen_V1.1", "BooGoo.Melamori.1"),
    ("BooGoo.Neki_V1.1", "BooGoo.Neeko.1"),
    ("BooGoo.Aoliva_Dun.1", "BooGoo.Olivia Dunne.1"),
    ("BooGoo.selena_v1.1", "BooGoo.Selena Gomez.1"),
    ("boyavam.Alyson_Hannigan.1", "boyavam.Alyson Hannigan.1"),
    ("boyavam.Anna_Kendrick.1", "boyavam.Anna Kendrick.1"),
    ("boyavam.Ariel_Winter.1", "boyavam.Ariel Winter.1"),
    ("boyavam.Avril_Lavigne.1", "boyavam.Avril Lavigne.1"),
    ("boyavam.Julie_Bowen.1", "boyavam.Julie Bowen.1"),
    ("boyavam.Lindsay_Lohan.1", "boyavam.Lindsay Lohan.1"),
    ("boyavam.MarCar.1", "boyavam.Mariah Carey.1"),
    ("boyavam.Miley_Cyrus.1", "boyavam.Miley Cyrus.1"),
    ("boyavam.Nicole_Scherzinger.1", "boyavam.Nicole Scherzinger.1"),
    ("boyavam.Sarah_Hyland.1", "boyavam.Sarah Hyland.1"),
    ("boyavam.Sofia_Vergara.1", "boyavam.Sofia Vergara.1"),
    ("boyavam.Stephanie_Beatriz.1", "boyavam.Stephanie Beatriz.1"),
    ("ChicoSuave.Abelluh_Dangur.1", "ChicoSuave.Abella Danger_v2.1"),
    ("ChicoSuave.AD.1", "ChicoSuave.Abella Danger.1"),
    ("ChicoSuave.Jazzelyn_Raye.1", "ChicoSuave.Addison Rae.1"),
    ("ChicoSuave.AOsee.1", "ChicoSuave.Alexandria Ocasio-Cortez.1"),
    ("ChicoSuave.Angella_Whyte.1", "ChicoSuave.Angela White.1"),
    ("ChicoSuave.Areeana_Grawnde.1", "ChicoSuave.Ariana Grande.1"),
    ("ChicoSuave.Aubree_Plazza.1", "ChicoSuave.Aubrey Plaza.1"),
    ("ChicoSuave.Ariel_BellaV2.1", "ChicoSuave.Bella Hadid.1"),
    ("ChicoSuave.Bell_Delfeen.1", "ChicoSuave.Belle Delphine.1"),
    ("ChicoSuave.Brinda_Sawng.1", "ChicoSuave.Brenda Song.1"),
    ("ChicoSuave.Brittanee_Spearz_-_Body.1", "ChicoSuave.Britney Spears.1"),
    ("ChicoSuave.Chelsea.3", "ChicoSuave.Chelsea Rae.3"),
    ("ChicoSuave.Chloey_Grayse_Moritz.1", "ChicoSuave.Chloe Grace Moretz.1"),
    ("ChicoSuave.Deekota_Sky.1", "ChicoSuave.Dakota Skye.1"),
    ("ChicoSuave.Topanguh.1", "ChicoSuave.Danielle Fishel.1"),
    ("ChicoSuave.DemeeHawx.1", "ChicoSuave.Demi Hawk.1"),
    ("ChicoSuave.Aliza_Eberra.1", "ChicoSuave.Eliza Ibarra.1"),
    ("ChicoSuave.Aliza_Eberra_v2.1", "ChicoSuave.Eliza Ibarra_v2.1"),
    ("ChicoSuave.Elsuh_Jeen.2", "ChicoSuave.Elsa Jean.2"),
    ("ChicoSuave.Emmuh_Wattsen_V2.1", "ChicoSuave.Emma Watson_v2.1"),
    ("ChicoSuave.EmmuhWattsen.1", "ChicoSuave.Emma Watson.1"),
    ("ChicoSuave.Fayy_Regan1.1", "ChicoSuave.Fay Reagan.1"),
    ("ChicoSuave.Gahl_Ghadot_Chico.1", "ChicoSuave.Gal Gadot.1"),
    ("ChicoSuave.GeannaDeorV2_faceUPDATED.1", "ChicoSuave.Gianna Dior_v2.1"),
    ("ChicoSuave.Keeanna_Deorr.1", "ChicoSuave.Gianna Dior.1"),
    ("ChicoSuave.Geena_Valinteena.1", "ChicoSuave.Gina Valentina.1"),
    ("ChicoSuave.Gryymez.1", "ChicoSuave.Grimes.1"),
    ("ChicoSuave.Jenifer_Annistan_v2.1", "ChicoSuave.Jennifer Aniston_v2.1"),
    ("ChicoSuave.Jenifer_Annistan_v2_Alt.1", "ChicoSuave.Jennifer Aniston_v2_alt.1"),
    ("ChicoSuave.Jennifur_Annistan.1", "ChicoSuave.Jennifer Aniston.1"),
    ("ChicoSuave.Jennifur_Annistan_UpgradedText.1", "ChicoSuave.Jennifer Aniston_alt.1"),
    ("ChicoSuave.Jennifur_Connally.1", "ChicoSuave.Jennifer Connely.1"),
    ("ChicoSuave.Jenifer_Laurence.1", "ChicoSuave.Jennifer Lawrence.1"),
    ("ChicoSuave.Jenifur_Lowpez_v1.1", "ChicoSuave.Jennifer Lopez.1"),
    ("ChicoSuave.Jessie_Beel.1", "ChicoSuave.Jessica Biel.1"),
    ("ChicoSuave.Kayte_Bekinsale.1", "ChicoSuave.Kate Beckinsale.1"),
    ("ChicoSuave.Cate_Uppton.1", "ChicoSuave.Kate Upton.1"),
    ("ChicoSuave.Chloey_Capri.1", "ChicoSuave.Khloe Kapri.1"),
    ("ChicoSuave.KimV1.1", "ChicoSuave.Kim Kardashian.1"),
    ("ChicoSuave.Lhana_Rodes.1", "ChicoSuave.Lana Rhoades.1"),
    ("ChicoSuave.Lexee_Bell.1", "ChicoSuave.Lexi Belle.1"),
    ("ChicoSuave.Linsey_Rohan.1", "ChicoSuave.Lindsay Lohan.1"),
    ("ChicoSuave.Liza.1", "ChicoSuave.Liza Rowe.1"),
    ("ChicoSuave.LL_CS.1", "ChicoSuave.Lupe Fuentes.1"),
    ("ChicoSuave.McKenzie_Maze.1", "ChicoSuave.Mackenzie Mace.1"),
    ("ChicoSuave.Madisun_Beers.1", "ChicoSuave.Madison Beer.1"),
    ("ChicoSuave.MyaWolf_limbs.1", "ChicoSuave.Maya Wolff.1"),
    ("ChicoSuave.Megin_Foxx.1", "ChicoSuave.Megan Fox.1"),
    ("ChicoSuave.Mea_Kaleefa_v2_-_Body.1", "ChicoSuave.Mia Khalifa_v2.1"),
    ("ChicoSuave.Meea_Kaleefa.1", "ChicoSuave.Mia Khalifa.1"),
    ("ChicoSuave.Mea_Malkovah.1", "ChicoSuave.Mia Malkova.1"),
    ("ChicoSuave.Meela_Kuhnis.1", "ChicoSuave.Mila Kunis.1"),
    ("ChicoSuave.Mylie_Sirus.1", "ChicoSuave.Miley Cyrus.1"),
    ("ChicoSuave.MylieSirus_V2.1", "ChicoSuave.Miley Cyrus_v2.1"),
    ("ChicoSuave.ZM_CS.2", "ChicoSuave.Miley Cyrus.2"),
    ("ChicoSuave.Rheese_Withurspoon.1", "ChicoSuave.Reese Witherspoon.1"),
    ("ChicoSuave.Rheese_Withurspoon_UpgradedText.1", "ChicoSuave.Reese Witherspoon_alt.1"),
    ("ChicoSuave.Rheese_Withurspoon_v5.1", "ChicoSuave.Reese Witherspoon_v2.1"),
    ("ChicoSuave.Remi_Lacroy.2", "ChicoSuave.Remy Lacroix.2"),
    ("ChicoSuave.Reeyanna_CS.1", "ChicoSuave.Rihanna.1"),
    ("ChicoSuave.Reeyanna_Preg.1", "ChicoSuave.Rihanna_preg.1"),
    ("ChicoSuave.Rylie_Reed.1", "ChicoSuave.Riley Reid.1"),
    ("ChicoSuave.Sarah_Rider.1", "ChicoSuave.Sarah Ryder.1"),
    ("ChicoSuave.Skarlett_Johanson.1", "ChicoSuave.Scarlett Johansson.1"),
    ("ChicoSuave.Serena_Gomes.1", "ChicoSuave.Selena Gomez.1"),
    ("ChicoSuave.Tayler_Swifft.1", "ChicoSuave.Taylor Swift.1"),
    ("Fernn.AlexO.1", "Fernn.Alexandria Ocasio-Cortez.1"),
    ("Fernn.A-linity.1", "Fernn.Alinity.1"),
    ("Fernn.SAnita.1", "Fernn.Anita Asmr.1"),
    ("Fernn.BelleD.1", "Fernn.Belle Delphine.1"),
    ("Fernn.BobaW.1", "Fernn.Boba W.1"),
    ("Fernn.DeniseR.1", "Fernn.Denise Richards.1"),
    ("Fernn.DizzyK.1", "Fernn.Dizzy K.1"),
    ("Fernn.FayeR.1", "Fernn.Faye R.1"),
    ("Fernn.FrivF.1", "Fernn.Friv F.1"),
    ("Fernn.GiadaR.1", "Fernn.Giada R.1"),
    ("Fernn.JojoS.1", "Fernn.Jojo S.1"),
    ("Fernn.KateM.1", "Fernn.Kate Middleton.1"),
    ("Fernn.KateR.1", "Fernn.Kate R.1"),
    ("Fernn.KateW.1", "Fernn.Kate Winslet.1"),
    ("Fernn.LydiaSQ.1", "Fernn.Lydia Sq.1"),
    ("Fernn.MeghanM.1", "Fernn.Meghan Markle.1"),
    ("Fernn.SarahS.1", "Fernn.Sarah Silverman.1"),
    ("Fernn.ShaniaT.1", "Fernn.Shania Twain.1"),
    ("Fernn.ASMRShine.1", "Fernn.Shine Asmr.1"),
    ("Fernn.TinaF.1", "Fernn.Tina Fey.1"),
    ("Fernn.TulsiG.1", "Fernn.Tulsi Gabbard.1"),
    ("GilgameshVR.AriAnnaV1.1", "GilgameshVR.Ariana Grande.1"),
    ("GilgameshVR.AriAnnaV2.1", "GilgameshVR.Ariana Grande_v2.1"),
    ("GilgameshVR.AriAnnaV3.1", "GilgameshVR.Ariana Grande_v3.1"),
    ("GilgameshVR.Barbie2.1", "GilgameshVR.Margot Robbie.1"),
    ("JoyBoy.Bella_Del.1", "JoyBoy.Belle Delphine.1"),
    ("JoyBoy.Bella_Tez.3", "JoyBoy.Belle Delphine.3"),
    ("KarmageddonVAM.Al3xandr1a0cas10_KARVAM.1", "KarmageddonVAM.Alexandria Ocasio-Cortez.1"),
    ("KarmageddonVAM.M3GAN_AI_KARVAM.2", "KarmageddonVAM.Amie Donald.2"),
    ("KarmageddonVAM.DameronCiazKARVAM.1", "KarmageddonVAM.Cameron Diaz.1"),
    ("KarmageddonVAM.BellyKundyKARVAM.2", "KarmageddonVAM.Christina Applegate.2"),
    ("KarmageddonVAM.Cyb1llSh3ph3rdKARVAM.1", "KarmageddonVAM.Cybill Shepherd.1"),
    ("KarmageddonVAM.D3bbyRyannKARVAM.2", "KarmageddonVAM.Debby Ryan.2"),
    ("KarmageddonVAM.DericaLuranceVARVAM.1", "KarmageddonVAM.Erica Durance.1"),
    ("KarmageddonVAM.FrannDr3sch3rKARVAM.1", "KarmageddonVAM.Fran Drescher.1"),
    ("KarmageddonVAM.GabriellaHertzV2KARVAM.1", "KarmageddonVAM.Gabriella Hertz.1"),
    ("KarmageddonVAM.CenniferJonnellyYoungKARVAM.1", "KarmageddonVAM.Jennifer Connely.1"),
    ("KarmageddonVAM.JCModPackv2.1", "KarmageddonVAM.Jennifer Connely_v2.1"),
    ("KarmageddonVAM.DessicaJunphyKARVAM.1", "KarmageddonVAM.Jessica Dunphy.1"),
    ("KarmageddonVAM.JKRHarriPutter2KARVAM.1", "KarmageddonVAM.Jk Rowling.1"),
    ("KarmageddonVAM.ElaineBSenfV2KARVAM.1", "KarmageddonVAM.Julia Louis-Dreyfus.1"),
    ("KarmageddonVAM.KaamalaHKARVAM.1", "KarmageddonVAM.Kamala Harris.1"),
    ("KarmageddonVAM.BeggyPundyV2KARVAM.1", "KarmageddonVAM.Katey Sagal.1"),
    ("KarmageddonVAM.PattyKerryKARVAM.1", "KarmageddonVAM.Katy Perry.1"),
    ("KarmageddonVAM.May1mB_AmyBBTKARVAM.1", "KarmageddonVAM.Mayim Bialik.1"),
    ("KarmageddonVAM.MeeganMaarkleKARVAM.1", "KarmageddonVAM.Megan Marhkle.1"),
    ("KarmageddonVAM.MaiFhalifaKARVAM.1", "KarmageddonVAM.Mia Khalifa.1"),
    ("KarmageddonVAM.Patr1c1aH3at0nKARVAM.1", "KarmageddonVAM.Patricia Heaton.1"),
    ("KarmageddonVAM.SP!1nkKARVAM.1", "KarmageddonVAM.Pink.1"),
    ("KarmageddonVAM.TeaaLeoniiKARVAM.1", "KarmageddonVAM.Tea Leoni.1"),
    ("KarmageddonVAM.T1ffan1Th13ss3nKARVAM.1", "KarmageddonVAM.Tiffani Thiessen.1"),
    ("KyussVii.AnnaHillVii.2", "KyussVii.Anna Hill.2"),
    ("KyussVii.TheKenducVii.2", "KyussVii.Anna Kendrick.2"),
    ("KyussVii.AnFindawayVii.1", "KyussVii.Anne Hathaway.1"),
    ("KyussVii.AshRobbVii.1", "KyussVii.Ashley Graham.1"),
    ("KyussVii.DallasVii.1", "KyussVii.Bryce Dallas Howard.1"),
    ("KyussVii.HendruckVii.1", "KyussVii.Christina Hendricks.1"),
    ("KyussVii.CawFurdVii.1", "KyussVii.Cindy Crawford.1"),
    ("KyussVii.HelisandreVii.1", "KyussVii.Clarice Van Houten.1"),
    ("KyussVii.ClemePoVii.1", "KyussVii.Clemence Poesy.1"),
    ("KyussVii.OpheliaVii.1", "KyussVii.Daisy Ridley_young.1"),
    ("KyussVii.TheRyderVii.1", "KyussVii.Daisy Ridley.1"),
    ("KyussVii.OwlsenReWorkVii.1", "KyussVii.Elizabeth Olsen_v2.1"),
    ("KyussVii.WitchVii.1", "KyussVii.Elizabeth Olsen.1"),
    ("KyussVii.KaSleazyVii.1", "KyussVii.Emilia Clarke.1"),
    ("KyussVii.GemWattVii.1", "KyussVii.Emma Watson.1"),
    ("KyussVii.WhatsunBeachVii.1", "KyussVii.Emma Watson_v2.1"),
    ("KyussVii.EricaCravenVii.1", "KyussVii.Erica Draven.1"),
    ("KyussVii.TheMenDezVii.1", "KyussVii.Eva Mendes.1"),
    ("KyussVii.GillAndeVii.1", "KyussVii.Gillian Anderson.1"),
    ("KyussVii.HaileyBurrieVii.2", "KyussVii.Halle Berry.2"),
    ("KyussVii.JaiPreVii.1", "KyussVii.Jaime Pressly.1"),
    ("KyussVii.AnistenVii.1", "KyussVii.Jennifer Aniston.1"),
    ("KyussVii.JennLopeVii.1", "KyussVii.Jennifer Lopez.1"),
    ("KyussVii.JLHVII.1", "KyussVii.Jennifer Love Hewitt.1"),
    ("KyussVii.BielVii.1", "KyussVii.Jessica Biel.1"),
    ("KyussVii.MrsBloomVii.1", "KyussVii.Katy Perry.1"),
    ("KyussVii.KnighteyVii.1", "KyussVii.Kiera Knightley.1"),
    ("KyussVii.KylieVii.2", "KyussVii.Kylie Jenner.2"),
    ("KyussVii.ThePewsterVii.1", "KyussVii.Lena Heady.1"),
    ("KyussVii.TheLowhandVii.1", "KyussVii.Lindsay Lohan.1"),
    ("KyussVii.LisFoiViiC.1", "KyussVii.Lisa Foiles.1"),
    ("KyussVii.TheRobbyVii.1", "KyussVii.Margot Robbie.1"),
    ("KyussVii.MinaCoolNessVii.1", "KyussVii.Mila Kunis.1"),
    ("KyussVii.PhoneSquirrelVii.1", "KyussVii.Milana Vayntrub.1"),
    ("KyussVii.SmirkFuVii.1", "KyussVii.Natalie Dormer.1"),
    ("KyussVii.NatPorVii.1", "KyussVii.Natalie Portman.1"),
    ("KyussVii.WildOlivesVii.1", "KyussVii.Olivia Wilde.1"),
    ("KyussVii.PenelopeViiA.1", "KyussVii.Penelope Cruz.1"),
    ("KyussVii.TheSanchezVii.1", "KyussVii.Roselyn Sanchez.1"),
    ("KyussVii.SalHayVii.1", "KyussVii.Salma Hayek.1"),
    ("KyussVii.HylanderVii.1", "KyussVii.Sarah Hyland.1"),
    ("KyussVii.VugeraVii.1", "KyussVii.Sofia Vergara.1"),
    ("KyussVii.SemStorVii.1", "KyussVii.Sophia Turner.1"),
    ("KyussVii.TessaFowlerBVii.1", "KyussVii.Tessa Fowler.1"),
    ("KyussVii.TheFoulerVii.1", "KyussVii.Tessa Fowler_v2.1"),
    ("KyussVii.TrishVii.1", "KyussVii.Trish Stratus.1"),
    ("KyussVii.TheJusticeVii.1", "KyussVii.Victoria Justice.1"),
    ("KyussVii.KendahyaVii.1", "KyussVii.Zendaya Coleman.1"),
    ("MCP.Look_313_Addy_Tlyn.1", "MCP.Addison Timlin.1"),
    ("MCP.Look_386_Amorenth.1", "MCP.Amouranth.1"),
    ("MCP.Look_311_Ema_Dmas.1", "MCP.Ana De Armas.1"),
    ("MCP.Look_352_Dokata_Fenning.1", "MCP.Dakota Fanning.1"),
    ("MCP.Look_343_Kulay_Coco.1", "MCP.Kaley Cuoco.1"),
    ("MCP.Look_349_Pokemone.1", "MCP.Pokimane Imane Anys.1"),
    ("MCP.Look_327_Xandrea_Dulock.1", "MCP.Sandra Bullock.1"),
    ("MCP.Look_341_Seorsa_Ronun.1", "MCP.Saoirse Ronan.1"),
    ("MCP.Look_394_Gina_Colony.1", "MCP.Sarah Wayne Callies.1"),
    ("Niko3DX.Rory_0313.3", "Niko3DX.Alexis Bledel.3"),
    ("Niko3DX.Anna_1214.2", "Niko3DX.Anna Kendrick.2"),
    ("Niko3DX.AvrilL_220305.1", "Niko3DX.Avril Lavigne.1"),
    ("Niko3DX.Brit_220201.1", "Niko3DX.Britney Spears.1"),
    ("Niko3DX.Dallas_220207.3", "Niko3DX.Bryce Dallas Howard.3"),
    ("Niko3DX.Laeya_1218.2", "Niko3DX.Carrie Fisher.2"),
    ("Niko3DX.Gilmore_0312.3", "Niko3DX.Gilmore Girls.3"),
    ("Niko3DX.Pepper_v2_0215.1", "Niko3DX.Gwyneth Paltrow.1"),
    ("Niko3DX.J_love_220318.1", "Niko3DX.Jennifer Love Hewitt.1"),
    ("Niko3DX.Miley_0130.3", "Niko3DX.Miley Cyrus.3"),
    ("Niko3DX.Taylor_1010.3", "Niko3DX.Taylor Swift.3"),
    ("Niko3DX.Taylor_210416.4", "Niko3DX.Taylor Swift.4"),
    ("PeteyTheKittler.DolphinBeauty.1", "PeteyTheKittler.Belle Delphine.1"),
    ("PL_Artists.ElsaJeansv2.2", "PL_Artists.Elsa Jean.2"),
    ("PL_Artists.Reese.1", "PL_Artists.Reese Witherspoon.1"),
    ("PL_Artists.Sasa_Gray.1", "PL_Artists.Sasha Gray.1"),
    ("PodFlower.Foxy_Momma.1", "PodFlower.Joanna Gaines.1"),
    ("PodFlower.Lil_Snuk.2", "PodFlower.Nicole Polizzi.2"),
    ("Riggins.GGD.1", "Riggins.Becky Lynch.1"),
    ("Riggins.Beth.1", "Riggins.Beth Curry.1"),
    ("Riggins.JS.2", "Riggins.Jada Stevens.2"),
    ("Riggins.KP.3", "Riggins.Katy Perry.3"),
    ("Riggins.KK.1", "Riggins.Kim Kardashian.1"),
    ("Riggins.MF.1", "Riggins.Megan Fox.1"),
    ("Riggins.NM.1", "Riggins.Nikki Minaj.1"),
    ("Riggins.Riggins_SH.1", "Riggins.Salma Hayek.1"),
    ("Rockseeker.wanda_classic.1", "Rockseeker.Elizabeth Olsen.1"),
    ("Shaper.Emys.2", "Shaper.Emma Stone.2"),
    ("Shaper.Hermi.1", "Shaper.Emma Watson.1"),
    ("Shaper.Edin.1", "Shaper.Evanna Lynch.1"),
    ("Shaper.Sanza.2", "Shaper.Sophia Turner.2"),
    ("Shaper.Tayls.1", "Shaper.Taylor Swift.1"),
    ("Shapes.Kat.2", "Shapes.Jennifer Lawrence.2"),
    ("Sirap.AlexBled.2", "Sirap.Alexis Bledel.2"),
    ("Sirap.AlyHan.1", "Sirap.Alyson Hannigan.1"),
    ("Sirap.AmandaB.1", "Sirap.Amanda Bynes.1"),
    ("Sirap.AmyAda.1", "Sirap.Amy Adams.1"),
    ("Sirap.AngJol.1", "Sirap.Angelina Jolie.1"),
    ("Sirap.ATJ.1", "Sirap.Anna Taylor Joy.1"),
    ("Sirap.AnHa.1", "Sirap.Anne Hathaway.1"),
    ("Sirap.AriWin.1", "Sirap.Ariel Winter.1"),
    ("Sirap.AvLav.1", "Sirap.Avril Lavigne.1"),
    ("Sirap.BritSpear.1", "Sirap.Britney Spears.1"),
    ("Sirap.CarVan.1", "Sirap.Carice Van Houten.1"),
    ("Sirap.ChrisHend.1", "Sirap.Christina Hendricks.1"),
    ("Sirap.DemiLove.1", "Sirap.Demi Lovato.1"),
    ("Sirap.ElizOls.1", "Sirap.Elizabeth Olsen.1"),
    ("Sirap.ElFan.1", "Sirap.Elle Fanning.1"),
    ("Sirap.EmSton.1", "Sirap.Emma Stone.1"),
    ("Sirap.EvaG.1", "Sirap.Eva Green.1"),
    ("Sirap.HilaDuff.1", "Sirap.Hillary Duff.1"),
    ("Sirap.IvaTru.1", "Sirap.Ivanka Trump.1"),
    ("Sirap.Pam.1", "Sirap.Jenna Fischer.1"),
    ("Sirap.JLo.1", "Sirap.Jennifer Lopez.1"),
    ("Sirap.JesAlb.1", "Sirap.Jessica Alba.1"),
    ("Sirap.KalCuo.1", "Sirap.Kaley Cuoco.1"),
    ("Sirap.KarGil.1", "Sirap.Karen Gillan.1"),
    ("Sirap.KatMar.1", "Sirap.Kate Mara.1"),
    ("Sirap.Sirap_KatUp.1", "Sirap.Kate Upton.1"),
    ("Sirap.KeiKni.2", "Sirap.Keira Knightley.2"),
    ("Sirap.KeJe.2", "Sirap.Kendall Jenner.2"),
    ("Sirap.KimKard.1", "Sirap.Kim Kardashian.1"),
    ("Sirap.KrisKreuk.1", "Sirap.Kristen Kreuk.1"),
    ("Sirap.KStew.1", "Sirap.Kristen Stewart.1"),
    ("Sirap.LauCoh.1", "Sirap.Lauren Cohan.1"),
    ("Sirap.LenHead.2", "Sirap.Lena Heady.2"),
    ("Sirap.LinLoh.1", "Sirap.Lindsay Lohan.1"),
    ("Sirap.LuLiu.1", "Sirap.Lucy Liu.1"),
    ("Sirap.AriaStork.1", "Sirap.Maisie Williams.1"),
    ("Sirap.BarbDoll.1", "Sirap.Margot Robbie.1"),
    ("Sirap.MarEliWin.1", "Sirap.Mary Elizabeth Winstead.1"),
    ("Sirap.MegFox.1", "Sirap.Megan Fox.1"),
    ("Sirap.MicTra.2", "Sirap.Michelle Trachtenberg.2"),
    ("Sirap.MilCyr.1", "Sirap.Miley Cyrus.1"),
    ("Sirap.NatDye.1", "Sirap.Natalia Dyer.1"),
    ("Sirap.NatDorm.2", "Sirap.Natalie Dormer.2"),
    ("Sirap.NicSch.1", "Sirap.Nicole Scherzinger.1"),
    ("Sirap.OlivMunn.1", "Sirap.Olivia Munn.1"),
    ("Sirap.OlivWild.1", "Sirap.Olivia Wilde.1"),
    ("Sirap.PaHi.1", "Sirap.Paris Hilton.1"),
    ("Sirap.RiRi.1", "Sirap.Rihanna.1"),
    ("Sirap.RosLes.1", "Sirap.Rose Leslie.1"),
    ("Sirap.SadSink.1", "Sirap.Sadie Sink.1"),
    ("Sirap.SanOh.1", "Sirap.Sandra Oh.1"),
    ("Sirap.SarHyl.1", "Sirap.Sarah Hyland.1"),
    ("Sirap.SelGom.2", "Sirap.Selena Gomez.2"),
    ("Sirap.SofiVerg.1", "Sirap.Sofia Vergara.1"),
    ("Sirap.SoTu.1", "Sirap.Sophia Turner.1"),
    ("Sirap.SydSwe.1", "Sirap.Sydney Sweeney.1"),
    ("Sirap.Sirap_TaySwi.1", "Sirap.Taylor Swift.1"),
    ("Sirap.VanHud.1", "Sirap.Vanessa Hudgens.1"),
    ("Sirap.ZoeDes.1", "Sirap.Zooey Deschanel.1"),
    ("Testitou.Aj-lee.1", "Testitou.Aj Lee Mendez.1"),
    ("Testitou.AlexaV2.1", "Testitou.Alexa Bliss.1"),
    ("Testitou.alicia.1", "Testitou.Alicia Fox.1"),
    ("Testitou.Billie.1", "Testitou.Billie Kay.1"),
    ("Testitou.carmella.1", "Testitou.Carmella Dale.1"),
    ("Testitou.kelly.1", "Testitou.Kelly Kelly.1"),
    ("Testitou.Kendra_Daniels.2", "Testitou.Kendra Daniels.2"),
    ("Testitou.Lana.1", "Testitou.Lana Perry.1"),
    ("Testitou.lita.1", "Testitou.Lita Dumas.1"),
    ("Testitou.Liv.1", "Testitou.Liv Morgan.1"),
    ("Testitou.Madison_Paige.1", "Testitou.Madison Paige.1"),
    ("Testitou.Melina.1", "Testitou.Melina Perez.1"),
    ("Testitou.mickie.1", "Testitou.Mickie James.1"),
    ("Testitou.Naomi.1", "Testitou.Naomi Mccray.1"),
    ("Testitou.Nikki.1", "Testitou.Nikki Garcia.1"),
    ("Testitou.paige.1", "Testitou.Paige Bevis.1"),
    ("Testitou.peyton.1", "Testitou.Peyton Royce.1"),
    ("Testitou.scarlett.1", "Testitou.Scarlett Bordeaux.1"),
    ("Testitou.Mcmahon.1", "Testitou.Stephanie Mcmahon.1"),
    ("Testitou.trish.1", "Testitou.Trish Stratus.1"),
    ("Torchmilk.Pink_haired_chick.1", "Torchmilk.Belle Delphine.1"),
    ("vecterror.Abella_Danger.1", "vecterror.Abella Danger.1"),
    ("vecterror.Abigail_Shapiro.1", "vecterror.Abigail Shapiro.1"),
    ("vecterror.Alba_Baptista.1", "vecterror.Alba Baptista.1"),
    ("vecterror.Alexandra_Daddario.1", "vecterror.Alexandra Daddario.1"),
    ("vecterror.Alexis_Bledel.2", "vecterror.Alexis Bledel.2"),
    ("vecterror.Alison_Brie.1", "vecterror.Alison Brie.1"),
    ("vecterror.Alyson_Hannigan.2", "vecterror.Alyson Hannigan.2"),
    ("vecterror.Alyssa_Milano.3", "vecterror.Alyssa Milano.3"),
    ("vecterror.Amanda_Bynes.1", "vecterror.Amanda Bynes.1"),
    ("vecterror.Amanda_Seyfried.1", "vecterror.Amanda Seyfried.1"),
    ("vecterror.Amber_Midthunder.1", "vecterror.Amber Midthunder.1"),
    ("vecterror.Amy_Adams.1", "vecterror.Amy Adams.1"),
    ("vecterror.Ana_de_Armas.1", "vecterror.Ana De Armas.1"),
    ("vecterror.Angela_Black.1", "vecterror.Angela Black.1"),
    ("vecterror.Angela_Sarafyan.1", "vecterror.Angela Sarafyan.1"),
    ("vecterror.Angelina_Jolie.1", "vecterror.Angelina Jolie.1"),
    ("vecterror.Anna_Kendrick.3", "vecterror.Anna Kendrick.3"),
    ("vecterror.Anna_Taylor_Joy.1", "vecterror.Anna Taylor Joy.1"),
    ("vecterror.Anne_Hathaway.1", "vecterror.Anne Hathaway.1"),
    ("vecterror.Annemarie.1", "vecterror.Anne Marie.1"),
    ("vecterror.Ariana_Grande.1", "vecterror.Ariana Grande.1"),
    ("vecterror.Ariel_Winter.1", "vecterror.Ariel Winter.1"),
    ("vecterror.Ashley_Olsen.1", "vecterror.Ashley Olsen.1"),
    ("vecterror.Aubrey_Plaza.1", "vecterror.Aubrey Plaza.1"),
    ("vecterror.Avril_Lavigne.1", "vecterror.Avril Lavigne.1"),
    ("vecterror.Aya_Cash.1", "vecterror.Aya Cash.1"),
    ("vecterror.Billie_Eilish.1", "vecterror.Billie Eilish.1"),
    ("vecterror.Brenda_Song.1", "vecterror.Brenda Song.1"),
    ("vecterror.Brie_Larson.1", "vecterror.Brie Larson.1"),
    ("vecterror.Britney_Spears.1", "vecterror.Britney Spears.1"),
    ("vecterror.Brittany_Snow.1", "vecterror.Brittany Snow.1"),
    ("vecterror.Bryce_Dallas_Howard.1", "vecterror.Bryce Dallas Howard.1"),
    ("vecterror.Carrie_Fisher.1", "vecterror.Carrie Fisher.1"),
    ("vecterror.Charlize_Theron.1", "vecterror.Charlize Theron.1"),
    ("vecterror.Chloe_Grace_Moretz.1", "vecterror.Chloe Grace Moretz.1"),
    ("vecterror.Christina_Aguilera.1", "vecterror.Christina Aguilera.1"),
    ("vecterror.Christina_Applegate.1", "vecterror.Christina Applegate.1"),
    ("vecterror.Christina_Ricci.1", "vecterror.Christina Ricci.1"),
    ("vecterror.Claudia_Schiffer.1", "vecterror.Claudia Schiffer.1"),
    ("vecterror.Cobie_Smulders.1", "vecterror.Cobie Smulders.1"),
    ("vecterror.Daisy_Ridley.2", "vecterror.Daisy Ridley.2"),
    ("vecterror.Dakota_Fanning.1", "vecterror.Dakota Fanning.1"),
    ("vecterror.Dominique_McElligott.1", "vecterror.Dominique Mcelligott.1"),
    ("vecterror.Eliza_Dushku.1", "vecterror.Eliza Dushku.1"),
    ("vecterror.Elizabeth_Olsen.1", "vecterror.Elizabeth Olsen.1"),
    ("vecterror.Elle_Fanning.1", "vecterror.Elle Fanning.1"),
    ("vecterror.Elsa_Jean.1", "vecterror.Elsa Jean.1"),
    ("vecterror.Emilia_Clarke.1", "vecterror.Emilia Clarke.1"),
    ("vecterror.Emily_Blunt.1", "vecterror.Emily Blunt.1"),
    ("vecterror.Emily_Browning.1", "vecterror.Emily Browning.1"),
    ("vecterror.Emily_Ratajkowski.1", "vecterror.Emily Ratajkowski.1"),
    ("vecterror.Emily_VanCamp.1", "vecterror.Emily Vancamp.1"),
    ("vecterror.Emma_Myers.1", "vecterror.Emma Myers.1"),
    ("vecterror.Emma_Roberts.1", "vecterror.Emma Roberts.1"),
    ("vecterror.Emma_Stone.1", "vecterror.Emma Stone.1"),
    ("vecterror.Emma_Watson.1", "vecterror.Emma Watson.1"),
    ("vecterror.Emmy_Rossum.1", "vecterror.Emmy Rossum.1"),
    ("vecterror.Erin_Moriarty.1", "vecterror.Erin Moriarty.1"),
    ("vecterror.Eva_Green.2", "vecterror.Eva Green.2"),
    ("vecterror.Eva_Mendes.1", "vecterror.Eva Mendes.1"),
    ("vecterror.Evangeline_Lilly.1", "vecterror.Evangeline Lilly.1"),
    ("vecterror.Felicity_Jones.1", "vecterror.Felicity Jones.1"),
    ("vecterror.Florence_Pugh.1", "vecterror.Florence Pugh.1"),
    ("vecterror.Foxy_Di.1", "vecterror.Foxy Di.1"),
    ("vecterror.Gabbie_Carter.1", "vecterror.Gabbie Carter.1"),
    ("vecterror.Gal_Gadot.1", "vecterror.Gal Gadot.1"),
    ("vecterror.Gemma_Arterton.1", "vecterror.Gemma Arterton.1"),
    ("vecterror.Gillian_Anderson.1", "vecterror.Gillian Anderson.1"),
    ("vecterror.Gillian_Jacobs.1", "vecterror.Gillian Jacobs.1"),
    ("vecterror.Gina_Carano.1", "vecterror.Gina Carano.1"),
    ("vecterror.Grace_Park.1", "vecterror.Grace Park.1"),
    ("vecterror.Greta_Thunberg.1", "vecterror.Greta Thunberg.1"),
    ("vecterror.Gwen_Stefani.1", "vecterror.Gwen Stefani.1"),
    ("vecterror.Gwyneth_Paltrow.1", "vecterror.Gwyneth Paltrow.1"),
    ("vecterror.Hailee_Steinfeld.1", "vecterror.Hailee Steinfeld.1"),
    ("vecterror.Hayden_Panettiere.1", "vecterror.Hayden Panettiere.1"),
    ("vecterror.Heather_Thomas.1", "vecterror.Heather Thomas.1"),
    ("vecterror.Holly_Marie_Combs.3", "vecterror.Holly Marie Combs.3"),
    ("vecterror.HoYeon_Jung.1", "vecterror.Hoyeon Jung.1"),
    ("vecterror.Iggy_Azalea.1", "vecterror.Iggy Azalea.1"),
    ("vecterror.Jane_Fonda.1", "vecterror.Jane Fonda.1"),
    ("vecterror.Jasmin_Wagner.1", "vecterror.Jasmin Wagner.1"),
    ("vecterror.Jenette_McCurdy.1", "vecterror.Jenette Mccurdy.1"),
    ("vecterror.Jenna_Fischer.1", "vecterror.Jenna Fischer.1"),
    ("vecterror.Jennie_Kim.1", "vecterror.Jennie Kim.1"),
    ("vecterror.Jennifer_Aniston.1", "vecterror.Jennifer Aniston.1"),
    ("vecterror.Jennifer_Connelly.1", "vecterror.Jennifer Connely.1"),
    ("vecterror.Jennifer_Lawrence.1", "vecterror.Jennifer Lawrence.1"),
    ("vecterror.Jennifer_Lopez.1", "vecterror.Jennifer Lopez.1"),
    ("vecterror.Jennifer_Love_Hewitt.1", "vecterror.Jennifer Love Hewitt.1"),
    ("vecterror.Jenny_Ortega.1", "vecterror.Jenny Ortega.1"),
    ("vecterror.Jessica_Alba.1", "vecterror.Jessica Alba.1"),
    ("vecterror.Joey_King.1", "vecterror.Joey King.1"),
    ("vecterror.Jordan_Capri.1", "vecterror.Jordan Capri.1"),
    ("vecterror.Julia_Garner.1", "vecterror.Julia Garner.1"),
    ("vecterror.Julie_Bowen.1", "vecterror.Julie Bowen.1"),
    ("vecterror.Kaley_Cuoco.1", "vecterror.Kaley Cuoco.1"),
    ("vecterror.Karen_Fukuhara.1", "vecterror.Karen Fukuhara.1"),
    ("vecterror.Karen_Gillan.1", "vecterror.Karen Gillan.1"),
    ("vecterror.KaSa_GrPa.3", "vecterror.Kasa Grpa.3"),
    ("vecterror.Kat_Dennings.1", "vecterror.Kat Dennings.1"),
    ("vecterror.Kate_Beckinsale.1", "vecterror.Kate Beckinsale.1"),
    ("vecterror.Kate_Mara.2", "vecterror.Kate Mara.2"),
    ("vecterror.Kate_Upton.1", "vecterror.Kate Upton.1"),
    ("vecterror.Katee_Owens.1", "vecterror.Katee Owens.1"),
    ("vecterror.Katee_Sackhoff.1", "vecterror.Katee Sackhoff.1"),
    ("vecterror.Katheryn_Winnick.1", "vecterror.Katheryn Winnick.1"),
    ("vecterror.Katy_Perry.1", "vecterror.Katy Perry.1"),
    ("vecterror.Keira_Knightley.1", "vecterror.Keira Knightley.1"),
    ("vecterror.Kelly_LeBrock.1", "vecterror.Kelly Lebrock.1"),
    ("vecterror.Kiernan_Shipka.2", "vecterror.Kiernan Shipka.2"),
    ("vecterror.Koto_Suzu.1", "vecterror.Koto Suzu.1"),
    ("vecterror.Kristen_Kreuk.1", "vecterror.Kristen Kreuk.1"),
    ("vecterror.Kristen_Stewart.1", "vecterror.Kristen Stewart.1"),
    ("vecterror.Krysten_Ritter.1", "vecterror.Krysten Ritter.1"),
    ("vecterror.Kylie_Minogue.1", "vecterror.Kylie Minogue.1"),
    ("vecterror.Lana_Li.1", "vecterror.Lana Li.1"),
    ("vecterror.Lauren_Cohan.1", "vecterror.Lauren Cohan.1"),
    ("vecterror.Lauren_Graham.1", "vecterror.Lauren Graham.1"),
    ("vecterror.Lea_Seydoux.1", "vecterror.Lea Seydoux.1"),
    ("vecterror.Lexi_Belle.1", "vecterror.Lexi Belle.1"),
    ("vecterror.Linda_Cardellini.1", "vecterror.Linda Cardellini.1"),
    ("vecterror.Lindsay_Lohan.1", "vecterror.Lindsay Lohan.1"),
    ("vecterror.Little_Caprice.1", "vecterror.Little Caprice.1"),
    ("vecterror.Liz_Vicious.1", "vecterror.Liz Vicious.1"),
    ("vecterror.Lucy_Liu.1", "vecterror.Lucy Liu.1"),
    ("vecterror.Lupe_Fuentes.1", "vecterror.Lupe Fuentes.1"),
    ("vecterror.Maisie_Williams.1", "vecterror.Maisie Williams.1"),
    ("vecterror.Margot_Robbie.1", "vecterror.Margot Robbie.1"),
    ("vecterror.Mariah_Carey.1", "vecterror.Mariah Carey.1"),
    ("vecterror.Marilyn_Monroe.1", "vecterror.Marilyn Monroe.1"),
    ("vecterror.Marisa_Tomei.2", "vecterror.Marisa Tomei.2"),
    ("vecterror.Mary_Elizabeth_Winstead.1", "vecterror.Mary Elizabeth Winstead.1"),
    ("vecterror.Mary_Kate_Olsen.1", "vecterror.Mary Kate Olsen.1"),
    ("vecterror.Maya_Hawke.1", "vecterror.Maya Hawke.1"),
    ("vecterror.Melissa_Fumero.1", "vecterror.Melissa Fumero.1"),
    ("vecterror.Melissa_Rauch.1", "vecterror.Melissa Rauch.1"),
    ("vecterror.Mena_Suvari.2", "vecterror.Mena Suvari.2"),
    ("vecterror.Mia_Khalifa.1", "vecterror.Mia Khalifa.1"),
    ("vecterror.Michelle_Monaghan.1", "vecterror.Michelle Monaghan.1"),
    ("vecterror.Michelle_Pfeiffer.1", "vecterror.Michelle Pfeiffer.1"),
    ("vecterror.Michelle_Rodriguez.2", "vecterror.Michelle Rodriguez.2"),
    ("vecterror.Michelle_Trachtenberg.1", "vecterror.Michelle Trachtenberg.1"),
    ("vecterror.Mila_Azul.1", "vecterror.Mila Azul.1"),
    ("vecterror.Mila_Kunis.1", "vecterror.Mila Kunis.1"),
    ("vecterror.Miley_Cyrus.1", "vecterror.Miley Cyrus.1"),
    ("vecterror.Millie_Bobby_Brown.3", "vecterror.Millie Bobby Brown.3"),
    ("vecterror.Milly_Alcock.1", "vecterror.Milly Alcock.1"),
    ("vecterror.Natalia_Dyer.1", "vecterror.Natalia Dyer.1"),
    ("vecterror.Natalie_Dormer.1", "vecterror.Natalie Dormer.1"),
    ("vecterror.Natalie_Portman.1", "vecterror.Natalie Portman.1"),
    ("vecterror.Missandei.1", "vecterror.Nathalie Emmanuel.1"),
    ("vecterror.Neek.1", "vecterror.Neeko.1"),
    ("vecterror.Nicki_Minaj.1", "vecterror.Nicki Minaj.1"),
    ("vecterror.Olivia_Wilde.1", "vecterror.Olivia Wilde.1"),
    ("vecterror.OlWi_TRON_light.2", "vecterror.Olwi Tron Light.2"),
    ("vecterror.Palina_Rojinski.1", "vecterror.Palina Rojinski.1"),
    ("vecterror.Paulina_Porizkova.1", "vecterror.Paulina Porizkova.1"),
    ("vecterror.Penelope_Cruz.1", "vecterror.Penelope Cruz.1"),
    ("vecterror.Peyton_List.1", "vecterror.Peyton List.1"),
    ("vecterror.Phoebe_Cates.1", "vecterror.Phoebe Cates.1"),
    ("vecterror.Piper_Perri_A.1", "vecterror.Piper Perri.1"),
    ("vecterror.Pokimane.1", "vecterror.Pokimane Imane Anys.1"),
    ("vecterror.Rebecca_Ferguson.1", "vecterror.Rebecca Ferguson.1"),
    ("vecterror.Rebel_Wilson.1", "vecterror.Rebel Wilson.1"),
    ("vecterror.Reese_Witherspoon.1", "vecterror.Reese Witherspoon.1"),
    ("vecterror.Remy_LaCroix.1", "vecterror.Remy Lacroix.1"),
    ("vecterror.Riley_Reid.1", "vecterror.Riley Reid.1"),
    ("vecterror.Rosario_Dawson.1", "vecterror.Rosario Dawson.1"),
    ("vecterror.Rose_Pike.1", "vecterror.Rose Pike.1"),
    ("vecterror.Sadie_Sink.1", "vecterror.Sadie Sink.1"),
    ("vecterror.Salma_Hayek.1", "vecterror.Salma Hayek.1"),
    ("vecterror.Sarah_Chalke.2", "vecterror.Sarah Chalke.2"),
    ("vecterror.Sarah_Hyland.1", "vecterror.Sarah Hyland.1"),
    ("vecterror.Sarah_Michelle_Gellar.2", "vecterror.Sarah Michelle Gellar.2"),
    ("vecterror.Scarlett_Johansson.1", "vecterror.Scarlett Johansson.1"),
    ("vecterror.Selena_Gomez.1", "vecterror.Selena Gomez.1"),
    ("vecterror.Shakira.1", "vecterror.Shakira Ripoll.1"),
    ("vecterror.Shania_Twain.1", "vecterror.Shania Twain.1"),
    ("vecterror.Shannen_Doherty.1", "vecterror.Shannen Doherty.1"),
    ("vecterror.Shannon_Elizabeth.1", "vecterror.Shannon Elizabeth.1"),
    ("vecterror.Sofía_Vergara.1", "vecterror.Sofia Vergara.1"),
    ("vecterror.Sophia_Lillis.1", "vecterror.Sophia Lillis.1"),
    ("vecterror.Sophie_Turner.1", "vecterror.Sophia Turner.1"),
    ("vecterror.Stephanie_Beatriz.1", "vecterror.Stephanie Beatriz.1"),
    ("vecterror.Summer_Glau.1", "vecterror.Summer Glau.1"),
    ("vecterror.Tania_Raymonde.1", "vecterror.Tania Raymonde.1"),
    ("vecterror.Tara_Reid.1", "vecterror.Tara Reid.1"),
    ("vecterror.Taylor_Swift.1", "vecterror.Taylor Swift.1"),
    ("vecterror.Terry_Farrell.1", "vecterror.Terry Farrell.1"),
    ("vecterror.Vanessa_Marano.1", "vecterror.Vanessa Marano.1"),
    ("vecterror.Winona_Ryder.1", "vecterror.Winona Ryder.1"),
    ("vecterror.Yolandi_Visser.1", "vecterror.Yolandi Visser.1"),
    ("vecterror.Yvonne_Strahovski.1", "vecterror.Yvonne Strahovski.1"),
    ("vecterror.Zendaya.1", "vecterror.Zendaya Coleman.1"),
    ("vecterror.Zoe_Saldana.1", "vecterror.Zoe Saldana.1"),
    ("Xspada.AvrilV4@Promo.1", "Xspada.Avril Lavigne.1"),
    ("Xspada.Targayen@Hard.1", "Xspada.Emilia Clarke.1"),
    ("Xspada.NieLa@Promo.1", "Xspada.Gwen Stefani.1"),
    ("Xspada.Lawr@Hard.1", "Xspada.Jennifer Lawrence.1"),
    ("Xspada.Lagertha2@Pub.1", "Xspada.Katheryn Winnick.1"),
    ("Xspada.Gomez2@Pub.1", "Xspada.Selena Gomez.1"),
    ("Xspada.Swift@Hard.1", "Xspada.Taylor Swift.1"),
    ("xxxa.Amie_by_xxxa.1", "xxxa.Amie.1"),
    ("xxxa.Amiliy_by_xxxa.1", "xxxa.Amiliy.1"),
    ("xxxa.Artesia_by_xxxa.1", "xxxa.Artesia.1"),
    ("xxxa.Atsushi_Eren_by_xxxa.1", "xxxa.Atsushi Eren.1"),
    ("xxxa.Eveline_by_xxxa.1", "xxxa.Eveline.1"),
    ("xxxa.Gina_by_xxxa.3", "xxxa.Gina.3"),
    ("xxxa.Hikaru_Aoyama_by_xxxa.3", "xxxa.Hikaru Aoyama.3"),
    ("xxxa.Hiroko_Tanaka_by_xxxa.2", "xxxa.Hiroko Tanaka.2"),
    ("xxxa.Ichika_Nagano_by_xxxa.1", "xxxa.Ichika Nagano.1"),
    ("xxxa.Ichita_Maomi_by_xxxa.1", "xxxa.Ichita Maomi.1"),
    ("xxxa.Ida_Michibe_by_xxxa.1", "xxxa.Ida Michibe.1"),
    ("xxxa.Inori_by_xxxa.1", "xxxa.Inori.1"),
    ("xxxa.Joan_D_Love_look.3", "xxxa.Joan D Love.3"),
    ("xxxa.Joi_by_xxxa.1", "xxxa.Joi.1"),
    ("xxxa.Julie_by_xxxa.13", "xxxa.Julie.13"),
    ("xxxa.LUNA_by_xxxa.5", "xxxa.Luna.5"),
    ("xxxa.Mai_by_xxxa.2", "xxxa.Mai.2"),
    ("xxxa.Mera_Asuki_by_xxxa.1", "xxxa.Mera Asuki.1"),
    ("xxxa.Mizuki_Takao_by_xxxa.1", "xxxa.Mizuki Takao.1"),
    ("xxxa.Muriel_by_xxxa.1", "xxxa.Muriel.1"),
    ("xxxa.Nagasawa_by_xxxa.3", "xxxa.Nagasawa.3"),
    ("xxxa.Naomi_by_xxxa.1", "xxxa.Naomi.1"),
    ("xxxa.Onaga_Ea_look.1", "xxxa.Onaga Ea.1"),
    ("xxxa.Pyo_Apple_by_xxxa.1", "xxxa.Pyo Apple.1"),
    ("xxxa.Rae_Black_by_xxxa.1", "xxxa.Rae Black.1"),
    ("xxxa.Raya_Steale_by_xxxa.1", "xxxa.Raya Steale.1"),
    ("xxxa.Rei_by_xxxa.1", "xxxa.Rei.1"),
    ("xxxa.Rizu_Nishi_by_xxxa.2", "xxxa.Rizu Nishi.2"),
    ("xxxa.SsunBK_by_xxxa.3", "xxxa.Ssun Bk.3"),
    ("xxxa.Timbo_Yurina_by_xxxa.4", "xxxa.Timbo Yurina.4"),
    ("xxxa.Tsugaru_Mikoto_by_xxxa.1", "xxxa.Tsugaru Mikoto.1"),
    ("xxxa.Vella_by_xxxa.1", "xxxa.Vella.1"),
    ("xxxa.Yoon_Yeram_by_xxxa.1", "xxxa.Yoon Yeram.1"),
    ("xxxa.Youka_Shumi_by_xxxa.2", "xxxa.Youka Shumi.2"),
    ("xxxa.Yua_Mikami_by_xxxa.2", "xxxa.Yua Mikami.2"),
    ("xxxa.Yume_Sonoda_by_xxxa.1", "xxxa.Yume Sonoda.1"),
    ("xxxa.Yuria_by_xxxa.3", "xxxa.Yuria.3"),
    ("Zeus.Brittany_Steers.1", "Zeus.Britney Spears.1"),
    ("Zombie_Siris.Alex_&_Lara.1", "Zombie_Siris.Alexandria Ocasio-Cortez And Lauren Boebert.1"),
    ("Zombie_Siris.Allie_Bell.1", "Zombie_Siris.Allison Belle.1"),
    ("Zombie_Siris.Alice_Williams.2", "Zombie_Siris.Allison Williams.2"),
    ("Zombie_Siris.Lilly_Von_Flute.1", "Zombie_Siris.Alyson Hannigan.1"),
    ("Zombie_Siris.Jolene_Angels_2.1", "Zombie_Siris.Angelina Jolie.1"),
    ("Zombie_Siris.Farrah_Anis__v2.1", "Zombie_Siris.Anna Faris.1"),
    ("Zombie_Siris.Alana_Hendricks.1", "Zombie_Siris.Anna Kendrick.1"),
    ("Zombie_Siris.Fanny_Fux.1", "Zombie_Siris.Annie Wersching.1"),
    ("Zombie_Siris.Stella_Azure.1", "Zombie_Siris.Brie Larson.1"),
    ("Zombie_Siris.Brooke_Thames.1", "Zombie_Siris.Brooke James.1"),
    ("Zombie_Siris.Lay_Uhh_Orgasma.1", "Zombie_Siris.Carrie Fisher.1"),
    ("Zombie_Siris.Charlene_Ron.1", "Zombie_Siris.Charlize Theron.1"),
    ("Zombie_Siris.Grace_Moore_V2.1", "Zombie_Siris.Chloe Grace Moretz.1"),
    ("Zombie_Siris.Raya_StarSprinter.1", "Zombie_Siris.Daisy Ridley.1"),
    ("Zombie_Siris.Topanda_2.1", "Zombie_Siris.Danielle Fishel.1"),
    ("Zombie_Siris.Kayden_Baker.1", "Zombie_Siris.Danielle Panabaker.1"),
    ("Zombie_Siris.Jessica_Paige.2", "Zombie_Siris.Deborah Ann Woll.2"),
    ("Zombie_Siris.Nepal_Richards.2", "Zombie_Siris.Denise Richards.2"),
    ("Zombie_Siris.Amanda_Waxhimov_Export1.1", "Zombie_Siris.Elizabeth Olsen.1"),
    ("Zombie_Siris.Ella_Evie_1.1", "Zombie_Siris.Ella Purnell.1"),
    ("Zombie_Siris.KayLeeC_V2.1", "Zombie_Siris.Emilia Clarke_v2.1"),
    ("Zombie_Siris.VAM_of_Thrones_-_KayLeeC.1", "Zombie_Siris.Emilia Clarke.1"),
    ("Zombie_Siris.Ellie_Holmes_V2.1", "Zombie_Siris.Emma Watson.1"),
    ("Zombie_Siris.Ellie_Holmes_V3.1", "Zombie_Siris.Emma Watson_v3.1"),
    ("Zombie_Siris.Erika_Progresso.1", "Zombie_Siris.Erica Lee.1"),
    ("Zombie_Siris.Gladys_Morphy.1", "Zombie_Siris.Evan Rachel Wood.1"),
    ("Zombie_Siris.Faith_VAM_Dyne_-_Hornyt.1", "Zombie_Siris.Evangeline Lilly.1"),
    ("Zombie_Siris.Felicity_Night_1.1", "Zombie_Siris.Felicia Day.1"),
    ("Zombie_Siris.Pam_Dresser.1", "Zombie_Siris.Fran Drescher.1"),
    ("Zombie_Siris.Ellen_Hunter.1", "Zombie_Siris.Helen Hunt_v2.1"),
    ("Zombie_Siris.Whory_Hunt.1", "Zombie_Siris.Helen Hunt.1"),
    ("Zombie_Siris.Nami_Marvani.2", "Zombie_Siris.Iman Vellani.2"),
    ("Zombie_Siris.Nami_Belta.3", "Zombie_Siris.Iman Zara.3"),
    ("Zombie_Siris.VAMder_Milfin_Anne_Peasley.1", "Zombie_Siris.Jenna Fischer.1"),
    ("Zombie_Siris.Ella_Marble.1", "Zombie_Siris.Jenna Marbles.1"),
    ("Zombie_Siris.Jenn_Orso.1", "Zombie_Siris.Jenna Ortega.1"),
    ("Zombie_Siris.Jan_Torrence.1", "Zombie_Siris.Jennifer Lawrence.1"),
    ("Zombie_Siris.Jan_Torrence_V2.1", "Zombie_Siris.Jennifer Lawrence_v2.1"),
    ("Zombie_Siris.Hot_Cocoa.1", "Zombie_Siris.Kaley Cuoco.1"),
    ("Zombie_Siris.Kara_Mate.1", "Zombie_Siris.Kate Mara.1"),
    ("Zombie_Siris.Katie_Bangford.1", "Zombie_Siris.Katherine Langford.1"),
    ("Zombie_Siris.Ruby_Jorgensen_v2.1", "Zombie_Siris.Katie Cassidy.1"),
    ("Zombie_Siris.VAMder_Milfin_Mandy_Kapurika.1", "Zombie_Siris.Kelly Kapoor.1"),
    ("Zombie_Siris.Karen_Karpka.2", "Zombie_Siris.Kiernan Shipka.2"),
    ("Zombie_Siris.Karen_Karpka_V2.2", "Zombie_Siris.Kiernan Shipka_v2.2"),
    ("Zombie_Siris.Kylie_Mulrooney.1", "Zombie_Siris.Kylie Jenner.1"),
    ("Zombie_Siris.Lana_PinchmyButti_V1.1", "Zombie_Siris.Laura Prepon.1"),
    ("Zombie_Siris.Lana_Pinchmybutti_V2.1", "Zombie_Siris.Laura Prepon_v2.1"),
    ("Zombie_Siris.Lara_VAMderport.1", "Zombie_Siris.Laura Vandervoort.1"),
    ("Zombie_Siris.Reah_Lemoni.2", "Zombie_Siris.Leah Remini.2"),
    ("Zombie_Siris.T_Rhonda_Lila.1", "Zombie_Siris.Leela Turanga.1"),
    ("Zombie_Siris.Ima_Britt_1.1", "Zombie_Siris.Lily Collins.1"),
    ("Zombie_Siris.Zelda_Kayak.1", "Zombie_Siris.Lucy Lawless.1"),
    ("Zombie_Siris.Francina_Lucciana.2", "Zombie_Siris.Ludovica Bizzaglia.2"),
    ("Zombie_Siris.Mags_Turnkey.1", "Zombie_Siris.Maggie Alexander.1"),
    ("Zombie_Siris.VAM_of_Thrones_-_Anya_Stork.1", "Zombie_Siris.Maisie Williams.1"),
    ("Zombie_Siris.Marge_Roberts_V2.1", "Zombie_Siris.Margot Robbie.1"),
    ("Zombie_Siris.Eve_Summer.1", "Zombie_Siris.Mary Elizabeth Winstead.1"),
    ("Zombie_Siris.Kira_La-Zur.1", "Zombie_Siris.Melissa Benoist.1"),
    ("Zombie_Siris.Mika_Lunis.2", "Zombie_Siris.Mila Kunis.2"),
    ("Zombie_Siris.Lola_Austin.1", "Zombie_Siris.Milla Jovich.1"),
    ("Zombie_Siris.Natasha_Rower_V2.1", "Zombie_Siris.Natalia Dyer.1"),
    ("Zombie_Siris.Jessa_LumberCreek.1", "Zombie_Siris.Natalie Dormer.1"),
    ("Zombie_Siris.VAM_of_Thrones_-_Maggie_Tyler.2", "Zombie_Siris.Natalie Dormer.2"),
    ("Zombie_Siris.PadThai_Amendolla.1", "Zombie_Siris.Natalie Portman.1"),
    ("Zombie_Siris.Liv14_Savage.1", "Zombie_Siris.Olivia Wilde.1"),
    ("Zombie_Siris.Liv14_Savage_V2.1", "Zombie_Siris.Olivia Wilde_v2.1"),
    ("Zombie_Siris.Fifer_Doe.1", "Zombie_Siris.Piper Fawn.1"),
    ("Zombie_Siris.RosieRays.1", "Zombie_Siris.Rosie Marcel.1"),
    ("Zombie_Siris.May_Maxfield.1", "Zombie_Siris.Sadie Sink.1"),
    ("Zombie_Siris.Sandy_Buttocks.2", "Zombie_Siris.Sandra Bullock.2"),
    ("Zombie_Siris.Violet_Raddshaw.4", "Zombie_Siris.Sarah Jessica Parker.4"),
    ("Zombie_Siris.Muffy_Slayer_2.1", "Zombie_Siris.Sarah Michelle Gellar.1"),
    ("Zombie_Siris.Shakey_Caderas_V2_-_Split.1", "Zombie_Siris.Shakira.1"),
    ("Zombie_Siris.Shelly_T_Burger.1", "Zombie_Siris.Shelley Hennig.1"),
    ("Zombie_Siris.VAM_of_Thrones_-_Sandy_Stork.1", "Zombie_Siris.Sophia Turner.1"),
    ("Zombie_Siris.Lady_Smash.1", "Zombie_Siris.Tatiana Maslany.1"),
    ("Zombie_Siris.Call_Me_Maevy.1", "Zombie_Siris.Thandiwe Newton.1"),
    ("Zombie_Siris.Chanel_Fran_DeZoé.1", "Zombie_Siris.Zooey Deschanel.1"),
]
