name: Package exe with PyInstaller - Windows

on: workflow_dispatch
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Checkout repo
      with:
        repository: phroz3ncode/dependency_manager@main
        path: src

    - name: PyInstaller Windows
      uses: ./.github/actions/pyinstaller
      with:
        path: src

    - uses: actions/upload-artifact@v2
      with:
        name: my-exe
        path: src/dist/windows # or path/to/artifact
