name: Package exe with PyInstaller - Windows

on: workflow_dispatch
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        path: src

    - name: PyInstaller Windows
      uses: ./src/.github/actions/pyinstaller

    - uses: actions/upload-artifact@v2
      with:
        name: my-exe
        path: ./src/dist/windows
